import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					href="https://fonts.googleapis.com/css2?family=Archivo:ital,wght@0,100..900;1,100..900&family=Geist:wght@100..900&display=swap"
					rel="stylesheet"
				/>
				<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
				<title>Blackmrkt</title>
			</head>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
