export const questions = [
	{
		id: "q1",
		text: "What is the main reason you came to BLACKMRKT?",
		type: "single_choice",
		options: [
			"I'm too busy to shop",
			"I want to find new brands and styles",
			"Shopping for someone",
			"I always had a passion for fashion",
			"I deserve a personal stylist",
		],
	},
	{
		id: "q2",
		text: "Before we begin what's your email",
		type: "email",
		note: "Include Google sign up button",
		placeholder: "Enter your email address",
	},
	{
		id: "q3",
		text: "How would you describe your style?",
		type: "single_choice",
		options: [
			"So fresh and so Clean, Classic & minimal",
			"Streetwear ( I belong to the streets)",
			"Vintage, alternative, contemporary",
			"Rockstar lifestyle",
		],
	},
	{
		id: "q4",
		text: "Which Fashion Icons share your sense of style?",
		type: "image_multiple_choice",
		note: "Consider using photos",
		options: [
			"Kanye West",
			"Tyler the Creator",
			"Ronnie Fieg",
			"Playboi Carti",
			"Justin Bieber",
			"Virgil Abloh",
		],
		images: {
			"Kanye West": "/images/Kanye_West.webp",
			"Tyler the Creator": "/images/Kanye_West.webp",
			"Ronnie Fieg": "/images/Kanye_West.webp",
			"Playboi Carti": "/images/Kanye_West.webp",
			"Justin Bieber": "/images/Kanye_West.webp",
			"Virgil Abloh": "/images/Kanye_West.webp",
		},
	},
	{
		id: "q5",
		text: "Which brands do you like?",
		type: "image_multiple_choice",
		note: "Insert logos from BLACKMRKT page",
		options: [
			"Nike",
			"Adidas",
			"Supreme",
			"Off-White",
			"Fear of God",
			"Essentials",
		],
		images: {
			Nike: "/images/nike-logo.png",
			Adidas: "/images/adidas-logo.png",
			Supreme: "/images/supreme-logo.png",
			"Off-White": "/images/offwhite-logo.png",
			"Fear of God": "/images/fog-logo.png",
			Essentials: "/images/essentials-logo.png",
		},
	},
	{
		id: "q6",
		text: "How tall are you?",
		type: "height",
		validation: {
			min: 1,
			max: 11,
		},
	},
	{
		id: "q7",
		text: "What's your weight?",
		type: "number",
		unit: "lbs",
		placeholder: "Enter your weight in lbs",
		validation: {
			min: 30,
			max: 1000,
		},
	},
	{
		id: "q8",
		text: "What size do you typically wear?",
		type: "size_group",
		subQuestions: [
			{
				id: "q8a",
				text: "Shirt",
				type: "single_choice",
				options: ["XS", "S", "M", "L", "XL", "XXL"],
			},
			{
				id: "q8b",
				text: "Waist",
				type: "single_choice",
				options: ["28", "30", "32", "34", "36", "38", "40"],
			},
			{
				id: "q8c",
				text: "Inseam",
				type: "single_choice",
				options: ["28", "30", "32", "34", "36"],
			},
			{
				id: "q8d",
				text: "Shoes",
				type: "single_choice",
				options: ["7", "8", "9", "10", "11", "12", "13"],
			},
		],
	},
	{
		id: "q9",
		text: "What type of pants do you rock?",
		type: "single_choice",
		options: ["Slim", "Relaxed", "Straight"],
	},
	{
		id: "q10",
		text: "Which colors do you want to avoid?",
		type: "color_multiple_choice",
		options: [
			"Black",
			"White",
			"Gray",
			"Brown",
			"Beige",
			"Pinks",
			"Green",
			"Red",
			"Olive",
			"Yellow",
		],
		colorCodes: {
			Black: "#000000",
			White: "#FFFFFF",
			Gray: "#808080",
			Brown: "#8B4513",
			Beige: "#F5F5DC",
			Pinks: "#FFC0CB",
			Green: "#008000",
			Red: "#FF0000",
			Olive: "#808000",
			Yellow: "#FFFF00",
		},
	},
	{
		id: "q11",
		text: "What designs do you like?",
		type: "single_choice",
		options: ["Basic", "Graphics", "Combination (drake voice)"],
	},
	{
		id: "q12",
		text: "Do you want your stylist to avoid any of these?",
		type: "text_multiple_choice",
		options: [
			"Polos",
			"Button Downs",
			"T-shirts",
			"Hoodies",
			"Jackets",
			"Shoes",
		],
	},
	{
		id: "q13",
		text: "Are you interested in vintage and second hand items in great and excellent condition?",
		type: "single_choice",
		options: ["Yes", "No"],
	},
	{
		id: "q14",
		text: "What's your monthly budget for clothing?",
		type: "number",
		unit: "$",
		placeholder: "Enter your monthly budget",
		validation: {
			min: 50,
			max: 10000,
		},
	},
	{
		id: "q15",
		text: "How often do you want to receive clothing?",
		type: "single_choice",
		options: ["Every two weeks", "Monthly", "Every two months"],
	},
];
